services:
  - type: web
    name: paradise-design-app
    env: docker
    plan: starter
    disk:
      name: paradise-design-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCOPES
        value: write_metaobject_definitions,write_metaobjects,write_products,write_files
      - key: DATABASE_URL
        value: file:/data/production.sqlite
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
