# Config produzione Netlify per paradise_design.

client_id = "42dc399cfbfed4bef0844ac123237b6b"
application_url = "https://paradise-public-app.netlify.app"
embedded = true
name = "paradise_design"

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_files"

[auth]
redirect_urls = [ "https://paradise-public-app.netlify.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
